### ISSUE TITLE
Offer the ability to format GitHub repo image links

### ISSUE THREAD

**Issue by lee-dohm** [mark-hahn/auto-host-markdown-image#1]
For example:
1. I have a Git repository that includes images in the `images/` directory, including `images/foo.jpg`
2. The Git repository is hosted on GitHub (easy enough to verify through remotes)
3. I have a Markdown file open from the same Git repository
4. Execute sequence to insert image into Markdown file
5. Insert image into Markdown file as `![Vanity tag](https://raw.githubusercontent.com/user-name/repo-name/master/images/foo.jpg)`

**Comment by mark-hahn** [comment]
I was excited to not have to deal with hosting in github. (grin)

Should I automatically use github for images in the repo or should I ask
them what they want?

**Comment by lee-dohm** [comment]
I was thinking if the image is already there, then it is simple ... not that you would have to deal with anything.

I'd say make it an alternate command like Alt-Drag or Alt-Click.

**Comment by mark-hahn** [comment]
Sounds cool.

> I was thinking if the image is already there, then it is simple

I think you will get out of the habit of putting it in the repo once you
use it for a while.  I surprised myself at how convenient it was when I
used it right now.  We don't have to worry about any hosting limits.  Imgur
specifically said you can request more traffic for a good cause.  Surely
they would appreciate the advertising in the developer community.

One more point:  using github means you lose the ability to see what it
looks like immediately and adjust the formatting.  It always bothered me
that I couldn't see the image in the atom preview until I pushed to the
repo.

But I always like another feature and this will help people that still want
to host with github.  Many will have the immediate reaction you did.
Although it only helps them type out the link when using github.

BTW, I'm thinking of removing the tree-selection option.  When putting in
the readme I realized it was complicated, unnecessary, and painful to use.
I didn't know you could drag an image to Atom.  That makes the drag/drop
even cooler.  What do you think?  I should pull it before many people
download it.

**Comment by lee-dohm** [comment]
Yeah, I think the tree-selection flow is overcomplicated.

**Comment by mark-hahn** [comment]
I removed the file-tree feature before anyone else downloaded it and I
changed the posting on the forum.  It is much better now.

I'd worry about the work lost but it was two days total.  And I've probably
thrown away more than 50% of the code I've written in my long lifetime.  On
my last paid project I had to rewrite ten's of thousands of lines of code
from scratch twice because of massive spec changes.  I didn't even bitch
because the pay was great.

My number of files is now half of what it was and my source line count has
shrunk even more.  It is now a simple little package.  It is harder to
write a good short story than it is to write a novel (according to some
famous author).

**Comment by mark-hahn** [comment]
On the original subject of this issue.

I didn't know you seriously cared about this until I noticed you took the trouble to move the bug-report GIF to github.  Why do you prefer github over other hosting?  I have two problems with github hosting which I have described before.

Instead of the workflow you suggested above, which would only save typing, I have a new idea.  I will have a configuration that says "Host from the project folder" and another that says "Project Relative Path To Image Folder" which will default to `./images`.  The usage will be the exact same drag/drop they do now for Imgur hosting. Then the package will create that path if necessary, copy the image to that folder, and insert the markdown text you described above.  If they are dragging an existing image from that existing folder then it will just skip the copy step and you'll get what you wanted from the beginning.  Sound good?

I have to deal with the package name problem.  I'm about to post a question on discuss.

**Comment by lee-dohm** [comment]
Sounds good, yes, thank you!

It's less that I prefer GitHub hosting over other hosting and more that I prefer the repository to contain everything to do with the project. And if the repository contains the master version, then it is easiest to reference the master version than to create a script that updates the hosted version, update the link if necessary and blah blah blah.

The reason I prefer the repository to contain everything to do with the project is, though it isn't common, I do occasionally work on projects offline or in situations where the Internet connection is less than stellar. Being able to work on whatever I need to is best for my workflow rather than doing half of it and then making a note for myself to come back and finish it later when the network is back up.

I agree that there are issues with the GitHub hosting of images and other similar assets. This is just the tradeoff I choose to make for my projects.

Thanks again for supporting my workflow :grinning:

**Comment by mark-hahn** [comment]
> I do occasionally work on projects offline or in situations where the
> Internet connection is less than stellar.

That is ironic since one the the two problems I have with github hosting is
that you can't see the image in markdown at all until you push the repo.
Pushing is kind of hard without the net.  (grin)

I'm working on this now.  Please check out my latest question on discuss
about how to rename this package.
